import {
  AlertTriangle,
  BadgeCheck,
  CheckCircle2,
  Clock,
  Cookie,
  CreditCard,
  Eye,
  FileText,
  Globe,
  Info,
  Leaf,
  Lock,
  Mail,
  MessageCircle,
  Package,
  RefreshCw,
  RotateCcw,
  Scale,
  Settings,
  ShieldCheck,
  Sparkles,
  Truck,
  Users,
  Wallet,
  Wrench,
  XCircle,
  type LucideIcon,
} from "lucide-react";
import type { PolicyIcon } from "@/lib/policy/types";

/** Central policy icon-key → lucide component map. Shared by the policy view and
 *  block renderers so a key resolves the same everywhere. */
export const policyIcon: Record<PolicyIcon, LucideIcon> = {
  sparkles: Sparkles,
  "check-circle": CheckCircle2,
  "x-circle": XCircle,
  "rotate-ccw": RotateCcw,
  clock: Clock,
  "shield-check": ShieldCheck,
  "message-circle": MessageCircle,
  mail: Mail,
  leaf: Leaf,
  "badge-check": BadgeCheck,
  truck: Truck,
  wallet: Wallet,
  "credit-card": CreditCard,
  package: Package,
  info: Info,
  "alert-triangle": AlertTriangle,
  lock: Lock,
  "file-text": FileText,
  eye: Eye,
  cookie: Cookie,
  settings: Settings,
  scale: Scale,
  users: Users,
  globe: Globe,
  "refresh-cw": RefreshCw,
  wrench: Wrench,
};
